### ISSUE TITLE
Instantiating class in django causing it to show JSON Decode Error

### ISSUE THREAD

**Issue by iamaakashbasnet** [basic-bgnr/NepseUnofficialApi#14]
@basic-bgnr 
Details:
nepse = Nepse() 👈

![Screenshot from 2024-06-24 08-04-59](https://github.com/basic-bgnr/NepseUnofficialApi/assets/136826895/32f7f0a2-c0aa-43e9-8136-c93096ebbbf4)

<pre>
➜ python manage.py runserver
Watching for file changes with StatReloader
Performing system checks...

Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/home/iamaakashbasnet/.pyenv/versions/3.12.3/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/home/iamaakashbasnet/.pyenv/versions/3.12.3/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/home/iamaakashbasnet/.pyenv/versions/3.12.3/envs/nepsevirt/lib/python3.12/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/home/iamaakashbasnet/.pyenv/versions/3.12.3/envs/nepsevirt/lib/python3.12/site-packages/django/core/management/commands/runserver.py", line 133, in inner_run
    self.check(display_num_errors=True)
  File "/home/iamaakashbasnet/.pyenv/versions/3.12.3/envs/nepsevirt/lib/python3.12/site-packages/django/core/management/base.py", line 485, in check
    all_issues = checks.run_checks(
                 ^^^^^^^^^^^^^^^^^^
  File "/home/iamaakashbasnet/.pyenv/versions/3.12.3/envs/nepsevirt/lib/python3.12/site-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/iamaakashbasnet/.pyenv/versions/3.12.3/envs/nepsevirt/lib/python3.12/site-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/iamaakashbasnet/.pyenv/versions/3.12.3/envs/nepsevirt/lib/python3.12/site-packages/django/core/checks/urls.py", line 24, in check_resolver
    return check_method()
           ^^^^^^^^^^^^^^
  File "/home/iamaakashbasnet/.pyenv/versions/3.12.3/envs/nepsevirt/lib/python3.12/site-packages/django/urls/resolvers.py", line 494, in check
    for pattern in self.url_patterns:
                   ^^^^^^^^^^^^^^^^^
  File "/home/iamaakashbasnet/.pyenv/versions/3.12.3/envs/nepsevirt/lib/python3.12/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/home/iamaakashbasnet/.pyenv/versions/3.12.3/envs/nepsevirt/lib/python3.12/site-packages/django/urls/resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
                       ^^^^^^^^^^^^^^^^^^^
  File "/home/iamaakashbasnet/.pyenv/versions/3.12.3/envs/nepsevirt/lib/python3.12/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/home/iamaakashbasnet/.pyenv/versions/3.12.3/envs/nepsevirt/lib/python3.12/site-packages/django/urls/resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/iamaakashbasnet/.pyenv/versions/3.12.3/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/iamaakashbasnet/Desktop/nepsevirt/backend/urls.py", line 12, in <module>
    path('officialapi/', include('v1.officialapi.urls')),
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/iamaakashbasnet/.pyenv/versions/3.12.3/envs/nepsevirt/lib/python3.12/site-packages/django/urls/conf.py", line 38, in include
    urlconf_module = import_module(urlconf_module)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/iamaakashbasnet/.pyenv/versions/3.12.3/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/iamaakashbasnet/Desktop/nepsevirt/v1/officialapi/urls.py", line 3, in <module>
    from .views.market import (
  File "/home/iamaakashbasnet/Desktop/nepsevirt/v1/officialapi/views/market.py", line 7, in <module>
    nepse = Nepse()
            ^^^^^^^
  File "/home/iamaakashbasnet/.pyenv/versions/3.12.3/envs/nepsevirt/lib/python3.12/site-packages/nepse/NepseLib.py", line 463, in __init__
    super().__init__(TokenManager, DummyIDManager)
  File "/home/iamaakashbasnet/.pyenv/versions/3.12.3/envs/nepsevirt/lib/python3.12/site-packages/nepse/NepseLib.py", line 38, in __init__
    self.load_json_api_end_points()
  File "/home/iamaakashbasnet/.pyenv/versions/3.12.3/envs/nepsevirt/lib/python3.12/site-packages/nepse/NepseLib.py", line 56, in load_json_api_end_points
    self.api_end_points = json.load(json_file)
                          ^^^^^^^^^^^^^^^^^^^^
  File "/home/iamaakashbasnet/.pyenv/versions/3.12.3/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/home/iamaakashbasnet/.pyenv/versions/3.12.3/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/iamaakashbasnet/.pyenv/versions/3.12.3/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/iamaakashbasnet/.pyenv/versions/3.12.3/lib/python3.12/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 40 column 1 (char 2232)
</pre>

**Comment by iamaakashbasnet** [comment]
For flask it seems to work fine.

**Comment by iamaakashbasnet** [comment]
![Screenshot from 2024-06-24 08-26-40](https://github.com/basic-bgnr/NepseUnofficialApi/assets/136826895/ab4bee8f-6c8f-46b8-8279-3c23fd8af1ce)

**Comment by basic-bgnr** [comment]
@iamaakashbasnet seems to be originated after your PR and I forgot to check the JSON file. It appears to have trailing comma, actual JSON spec doesn't permit comma at the end of last item, removing the comma would work. I'll push change tonight, mean time you can just delete it

**Comment by basic-bgnr** [comment]
PR here #15

**Comment by iamaakashbasnet** [comment]
Thanks for the update! @basic-bgnr
